name: create-docker-image
run-name: Create a new Dockerimage with the content of the pelican static site generator

on: push
  
jobs:
  verified_commit_check:
    name: Check for unverified commits
    runs-on: ubuntu-latest
    steps:
      - uses: nadock/verified_commits_check@v1

  build-docker-image:
    runs-on: ubuntu-latest
    needs: verified_commit_check
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pelican requirements
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: pip install -r requirements.txt

      - name: Make sure everything is clear
        run: make clean
        working-directory: ./pelican

      - name: Generate website content
        run: make publish
        working-directory: ./pelican

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: cfluegel/website-blog-flgl-tech
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD'}}
            type=sha
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
