name: create-docker-image
run-name: Create a new Dockerimage with the content of the pelican static site generator
on: [push]
jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pelican requirements
        uses: logikal-io/pip-install@v1.0.0
        with:
          requirements: pelican/requirements.txt

      - name: Make sure everything is clear
        run: make clean
        working-directory: ./pelican

      - name: Generate website content
        run: make publish
        working-directory: ./pelican

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: cfluegel/blog-flgl-tech
          tags: |
            type=raw,value=latest
            type=raw,value={{date 'YYYYMMDD'}}
            type=sha


      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: "."
          push: true
          tags: ${{ steps.meta.outputs.tags }}